CREATE TABLE IF NOT EXISTS info (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    age INTEGER NOT NUll,
    height FLOAT NOT NULL,
    weight FLOAT NOT NULL,
    systolic INTEGER NOT NULL,
    diastolic INTEGER NOT NULL
);